/**
 * Seed script - Luxury Cocktails & Shots
 * Run: npx ts-node -e "require('./lib/seedBeverages.ts')"
 * OR call the /api/admin/seed-beverages endpoint
 */

export const luxuryBeverages = [
  // ── COCKTAILS ──────────────────────────────────────────────
  {
    name: 'Midnight Noir',
    category: 'Cocktail',
    prices: { normal: 18, full: 22 },
    image: 'https://images.unsplash.com/photo-1470337458703-46ad1756a187?w=600&q=80',
    prepTime: '5 min',
    allergens: ['Sulfites'],
    isAvailable: true,
    description: 'Black vodka, activated charcoal syrup, fresh lime, topped with sparkling water. Mysteriously dark, dangerously smooth.',
  },
  {
    name: 'Golden Hour',
    category: 'Cocktail',
    prices: { normal: 20, full: 25 },
    image: 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=600&q=80',
    prepTime: '6 min',
    allergens: ['Sulfites', 'Eggs'],
    isAvailable: true,
    description: 'Aged rum, passion fruit, honey syrup, egg white foam, edible gold dust. A sip of sunset.',
  },
  {
    name: 'Velvet Rose',
    category: 'Cocktail',
    prices: { normal: 17, full: 21 },
    image: 'https://images.unsplash.com/photo-1587223962930-cb7f31384c19?w=600&q=80',
    prepTime: '5 min',
    allergens: ['Sulfites'],
    isAvailable: true,
    description: 'Gin, rose water, raspberry coulis, elderflower tonic. Floral, elegant, and unforgettable.',
  },
  {
    name: 'Azure Drift',
    category: 'Cocktail',
    prices: { normal: 19, full: 24 },
    image: 'https://images.unsplash.com/photo-1551538827-9c037cb4f32a?w=600&q=80',
    prepTime: '5 min',
    allergens: ['Sulfites'],
    isAvailable: true,
    description: 'Blue curaçao, coconut cream, pineapple juice, mint. Ocean in a glass.',
  },
  {
    name: 'Smoked Maple Old Fashioned',
    category: 'Cocktail',
    prices: { normal: 22, full: 28 },
    image: 'https://images.unsplash.com/photo-1527761939622-933c5d5a7c84?w=600&q=80',
    prepTime: '8 min',
    allergens: ['Sulfites'],
    isAvailable: true,
    description: 'Bourbon, maple syrup, smoked orange peel, Angostura bitters. Table-side smoke cloche presentation.',
  },
  {
    name: 'Sakura Sling',
    category: 'Cocktail',
    prices: { normal: 16, full: 20 },
    image: 'https://images.unsplash.com/photo-1560508179-b2c9a3555772?w=600&q=80',
    prepTime: '5 min',
    allergens: ['Sulfites'],
    isAvailable: true,
    description: 'Sake, cherry blossom syrup, yuzu juice, soda water. A delicate Japanese-inspired blend.',
  },
  {
    name: 'Espresso Martini Royale',
    category: 'Cocktail',
    prices: { normal: 19, full: 23 },
    image: 'https://images.unsplash.com/photo-1574073900378-4f64f3a11c22?w=600&q=80',
    prepTime: '6 min',
    allergens: ['Sulfites', 'Dairy'],
    isAvailable: true,
    description: 'Cold-brew espresso, Kahlúa, vanilla vodka, cream foam. The perfect nightcap.',
  },
  {
    name: 'Tropic Thunder',
    category: 'Cocktail',
    prices: { normal: 15, full: 18 },
    image: 'https://images.unsplash.com/photo-1606856110002-d0991ce78249?w=600&q=80',
    prepTime: '5 min',
    allergens: ['Sulfites'],
    isAvailable: true,
    description: 'Mango rum, chili-lime rim, ginger beer, fresh mango. Tropical heat with island coolness.',
    spiceLevel: 2,
  },

  // ── SHOTS ──────────────────────────────────────────────────
  {
    name: 'Gold Rush',
    category: 'Shot',
    prices: { normal: 9 },
    image: 'https://images.unsplash.com/photo-1615887085099-b5d4e42e7e64?w=600&q=80',
    prepTime: '2 min',
    allergens: ['Sulfites'],
    isAvailable: true,
    description: 'Tequila, goldschläger, honey. Smooth fire with a glimmer.',
  },
  {
    name: 'Black Widow',
    category: 'Shot',
    prices: { normal: 10 },
    image: 'https://images.unsplash.com/photo-1543007630-9710e4a00a20?w=600&q=80',
    prepTime: '2 min',
    allergens: ['Sulfites'],
    isAvailable: true,
    description: 'Jägermeister, black sambuca, Red Bull. Intense, bold, not for the faint-hearted.',
  },
  {
    name: 'Silk & Velvet',
    category: 'Shot',
    prices: { normal: 11 },
    image: 'https://images.unsplash.com/photo-1580927752452-89d86da3fa0a?w=600&q=80',
    prepTime: '2 min',
    allergens: ['Dairy', 'Sulfites'],
    isAvailable: true,
    description: 'Baileys Irish Cream layered over butterscotch schnapps. Dessert in a single sip.',
  },
  {
    name: 'Kamikaze',
    category: 'Shot',
    prices: { normal: 8 },
    image: 'https://images.unsplash.com/photo-1546171753-97d7676e4602?w=600&q=80',
    prepTime: '2 min',
    allergens: ['Sulfites'],
    isAvailable: true,
    description: 'Triple sec, lime juice, vodka. Classic, crisp, and legendary.',
  },
  {
    name: 'Dragon Fire',
    category: 'Shot',
    prices: { normal: 10 },
    image: 'https://images.unsplash.com/photo-1563227812-0ea4c22e6cc8?w=600&q=80',
    prepTime: '2 min',
    allergens: ['Sulfites'],
    isAvailable: true,
    description: 'Fireball cinnamon whisky, habanero tincture. Seriously hot — seriously good.',
    spiceLevel: 3,
  },
  {
    name: 'Lemon Drop',
    category: 'Shot',
    prices: { normal: 8 },
    image: 'https://images.unsplash.com/photo-1536935338788-846bb9981813?w=600&q=80',
    prepTime: '2 min',
    allergens: ['Sulfites'],
    isAvailable: true,
    description: 'Citrus vodka, lemon juice, sugar rim. Zesty and refreshing.',
  },
];
